"""Optional machine-learning scaffolding for AirDesk."""

from airdesk.ml.dataset import (
    TCN_FEATURE_COLUMNS,
    TCN_FEATURE_PRESETS,
    TCN_PHASE_TARGETS,
    TCN_STREAM_INVARIANT_FEATURE_COLUMNS,
    TCN_TARGET_ASSIGNMENTS,
    TCN_TARGET_MODES,
    TCN_TARGETS,
    TcnDatasetManifest,
    TcnFeatureSource,
    TcnWindowSample,
    build_tcn_dataset_manifest,
    feature_columns_for_preset,
    feature_window_matrix,
    load_feature_rows_csv,
    load_tcn_dataset_manifest,
    save_tcn_dataset_manifest,
    target_assignments,
    targets_for_mode,
)
from airdesk.ml.diagnostics import (
    FeatureDiagnosticsReport,
    FeatureFileDiagnostic,
    FeatureHoldoutSplit,
    build_feature_diagnostics_report,
    save_feature_diagnostics_report,
    split_feature_holdout,
)
from airdesk.ml.label_refinement import (
    RefinedGestureLabel,
    RefinedLabelFileResult,
    refine_motion_aligned_label_file,
)
from airdesk.ml.train import (
    CausalTcnLivePrediction,
    CausalTcnLivePredictor,
    CausalTcnPrediction,
    CausalTcnTrainingConfig,
    CausalTcnTrainingResult,
    MissingMlDependencyError,
    TcnTrainingArrays,
    predict_causal_tcn_manifest,
    prepare_tcn_training_arrays,
    train_causal_tcn,
)

__all__ = [
    "TCN_FEATURE_COLUMNS",
    "TCN_FEATURE_PRESETS",
    "TCN_PHASE_TARGETS",
    "TCN_STREAM_INVARIANT_FEATURE_COLUMNS",
    "TCN_TARGET_ASSIGNMENTS",
    "TCN_TARGETS",
    "TCN_TARGET_MODES",
    "TcnDatasetManifest",
    "TcnFeatureSource",
    "TcnWindowSample",
    "build_tcn_dataset_manifest",
    "feature_window_matrix",
    "feature_columns_for_preset",
    "FeatureDiagnosticsReport",
    "FeatureFileDiagnostic",
    "FeatureHoldoutSplit",
    "RefinedGestureLabel",
    "RefinedLabelFileResult",
    "load_feature_rows_csv",
    "load_tcn_dataset_manifest",
    "build_feature_diagnostics_report",
    "refine_motion_aligned_label_file",
    "CausalTcnPrediction",
    "CausalTcnLivePrediction",
    "CausalTcnLivePredictor",
    "CausalTcnTrainingConfig",
    "CausalTcnTrainingResult",
    "MissingMlDependencyError",
    "TcnTrainingArrays",
    "prepare_tcn_training_arrays",
    "predict_causal_tcn_manifest",
    "save_tcn_dataset_manifest",
    "target_assignments",
    "targets_for_mode",
    "save_feature_diagnostics_report",
    "split_feature_holdout",
    "train_causal_tcn",
]
